# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blackCon.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(774, 595)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(77)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("appIcon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #323232;\n"
"}\n"
"QPushButton\n"
"{\n"
"   \n"
"    background-color: rgb(85, 85, 255);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border-color:rgb(255, 255, 255);\n"
"    border-width: 1px;\n"
"}\n"
"QLineEdit\n"
"{\n"
"    border-width: 1px;\n"
"    border-radius: 6;\n"
"    border-style: solid;\n"
"    border-color: rgb(182, 194, 192);\n"
"}\n"
"QLineEdit:focus\n"
"{\n"
"    border-color: rgb(85, 85, 255);\n"
"    border-width: 1px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.urlInput = QtWidgets.QLineEdit(self.centralwidget)
        self.urlInput.setGeometry(QtCore.QRect(20, 40, 731, 20))
        self.urlInput.setText("")
        self.urlInput.setObjectName("urlInput")
        self.checkButton = QtWidgets.QPushButton(self.centralwidget)
        self.checkButton.setGeometry(QtCore.QRect(20, 70, 75, 23))
        self.checkButton.setStyleSheet("")
        self.checkButton.setObjectName("checkButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 181, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 47, 13))
        self.label_2.setObjectName("label_2")
        self.getResponseOption = QtWidgets.QCheckBox(self.centralwidget)
        self.getResponseOption.setGeometry(QtCore.QRect(130, 70, 141, 17))
        self.getResponseOption.setAcceptDrops(False)
        self.getResponseOption.setChecked(False)
        self.getResponseOption.setAutoRepeat(True)
        self.getResponseOption.setTristate(False)
        self.getResponseOption.setObjectName("getResponseOption")
        self.resultsBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.resultsBox.setGeometry(QtCore.QRect(20, 130, 731, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsBox.sizePolicy().hasHeightForWidth())
        self.resultsBox.setSizePolicy(sizePolicy)
        self.resultsBox.setStyleSheet("border-width: 1px;\n"
"    border-radius: 6;\n"
"    border-style: solid;\n"
"    border-color: rgb(182, 194, 192);")
        self.resultsBox.setObjectName("resultsBox")
        self.displayBodyOption = QtWidgets.QCheckBox(self.centralwidget)
        self.displayBodyOption.setGeometry(QtCore.QRect(260, 70, 91, 17))
        self.displayBodyOption.setObjectName("displayBodyOption")
        self.urlAnalysisOption = QtWidgets.QCheckBox(self.centralwidget)
        self.urlAnalysisOption.setGeometry(QtCore.QRect(360, 70, 131, 17))
        self.urlAnalysisOption.setObjectName("urlAnalysisOption")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 774, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuApp = QtWidgets.QMenu(self.menuBar)
        self.menuApp.setObjectName("menuApp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionThis_is_toll_for_check_your_url_security = QtWidgets.QAction(MainWindow)
        self.actionThis_is_toll_for_check_your_url_security.setObjectName("actionThis_is_toll_for_check_your_url_security")
        self.helpAction = QtWidgets.QAction(MainWindow)
        self.helpAction.setCheckable(True)
        self.helpAction.setObjectName("helpAction")
        self.exitAction = QtWidgets.QAction(MainWindow)
        self.exitAction.setObjectName("exitAction")
        self.menuApp.addAction(self.helpAction)
        self.menuApp.addAction(self.exitAction)
        self.menuBar.addAction(self.menuApp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BLACKCON"))
        self.checkButton.setText(_translate("MainWindow", "Check"))
        self.label.setText(_translate("MainWindow", "Enter the URL to verify security :"))
        self.label_2.setText(_translate("MainWindow", "Results :"))
        self.getResponseOption.setText(_translate("MainWindow", "Get response from url"))
        self.displayBodyOption.setText(_translate("MainWindow", "Display body"))
        self.urlAnalysisOption.setText(_translate("MainWindow", "Response analysis"))
        self.menuApp.setTitle(_translate("MainWindow", "App"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionThis_is_toll_for_check_your_url_security.setText(_translate("MainWindow", "This is toll for check your url security"))
        self.helpAction.setText(_translate("MainWindow", "Help"))
        self.exitAction.setText(_translate("MainWindow", "Exit"))
